import {Displayinfo} from '../displayinfo';
export const List: Displayinfo[] =[
  {id:1,
  name :'Raj Jadhav',
  photo :'http://gdurl.com/yS-K',
  year :'Head',
  facebooklk:'https://www.instagram.com/jadhavraj098/',
  twitterlk:'',
  instalk:'',
  linkedinlk:''
  },
  {id:2,
  name :'Mahesh Dhawale',
  photo :'http://gdurl.com/ZhyL',
  year :'BE',
  facebooklk:'https://www.facebook.com/mahesh.dhawale.372',
  twitterlk:'',
  instalk:'https://www.instagram.com/i_maheshd/',
  linkedinlk:'https://www.instagram.com/i_maheshd/'
  },
  {id:3,
  name :'Sumeet Bhamare',
  photo :'http://gdurl.com/7qRT',
  year :'BE',
  facebooklk:'https://www.facebook.com/sumeet.bhamare.1',
  twitterlk:'',
  instalk:'https://www.instagram.com/sumeet_bhamare/',
  linkedinlk:'https://www.linkedin.com/in/sumeet-bhamare-253ab8140/'
  },
  {id:4,
  name :'Rakshanda Parekh',
  photo :'http://gdurl.com/njDK',
  year :'BE',
  facebooklk:'https://www.facebook.com/rakshanda.parekh',
  twitterlk:'https://mobile.twitter.com/rakshandaparekh',
  instalk:'https://www.instagram.com/the_epic_messy/',
  linkedinlk:'https://www.linkedin.com/in/rakshanda-parekh-a06639150'
  },
  {id:5,
  name :'Ashay Chavan',
  photo :'http://gdurl.com/G5N4',
  year :'TE',
  facebooklk:'https://www.facebook.com/ashay.chavan.56',
  twitterlk:'',
  instalk:'https://www.instagram.com/ashay_chavan.11/',
  linkedinlk:''
  },
  {id:6,
  name :'Rasika Pangarkar',
  photo :'http://gdurl.com/8g88',
  year :'TE',
  facebooklk:'acebook.com/profile.php?id=100006301244975',
  twitterlk:'twitter.com/RasikaPangarkar?s=09',
  instalk:'https://www.instagram.com/rasikap98/',
  linkedinlk:'https://www.linkedin.com/in/rasika-pangarkar-83090b14a'
  },
  {id:7,
  name :'Venkatesh Kalokhe',
  photo :'http://gdurl.com/oW9z',
  year :'TE',
  facebooklk:'https://www.facebook.com/venkatesh.kalokhe',
  twitterlk:'https://mobile.twitter.com/venk_yy',
  instalk:'https://www.instagram.com/tablamaster.cpp/',
  linkedinlk:''
  },
  {id:8,
  name :'Ashutosh Alaskar',
  photo :'http://gdurl.com/YiNp',
  year :'SE',
  facebooklk:'https://www.facebook.com/ashutosh.alaskar',
  twitterlk:'',
  instalk:'https://www.instagram.com/ashutoshalaskar/',
  linkedinlk:''
  },
  {id:9,
  name :'Gautami Shaha',
  photo :'http://gdurl.com/caeG',
  year :'SE',
  facebooklk:'https://www.facebook.com/profile.php?id=100017007645592',
  twitterlk:'',
  instalk:'https://www.instagram.com/gautami_shaha/',
  linkedinlk:''
  }
];
