import {Displayinfo} from '../displayinfo';
export const List: Displayinfo[] =[
  {id:1,
  name :'Ketaki Kavatkar',
  photo :'http://gdurl.com/RZd0',
  year :'Head',
  facebooklk:'https://www.facebook.com/ketaki.kavatkar',
  twitterlk:'',
  instalk:'https://www.instagram.com/k.ketaki/',
  linkedinlk:'https://www.linkedin.com/in/ketaki-kavatkar-69b170177/'
  },
  {id:2,
  name :'Vishal Pazare',
  photo :'http://gdurl.com/ULC2',
  year :'BE',
  facebooklk:'https://www.facebook.com/profile.php?id=100008529854466',
  twitterlk:'',
  instalk:'https://www.instagram.com/vishalpazare/',
  linkedinlk:'https://www.linkedin.com/in/vishal-pazare-0b4129103'
  },
  {id:3,
  name :'Prachi Shingvi',
  photo :'http://gdurl.com/Nc7h',
  year :'BE',
  facebooklk:'',
  twitterlk:'',
  instalk:'',
  linkedinlk:'https://www.linkedin.com/in/prachi-shingvi'
  },
  {id:4,
  name :'Ajay Gaikwad',
  photo :'http://gdurl.com/v66B',
  year :'BE',
  facebooklk:'https://www.facebook.com/ajay.gaikwad.3701779',
  twitterlk:'https://twitter.com/Ajayg2808',
  instalk:'https://www.instagram.com/ajayg2808',
  linkedinlk:'https://www.linkedin.com/in/ajay-gaikwad-72658016a'
  },
  {id:5,
  name :'Deepak Chaudhari',
  photo :'http://gdurl.com/kmHN',
  year :'TE',
  facebooklk:'',
  twitterlk:'https://mobile.twitter.com/deepakcha151998',
  instalk:'https://www.instagram.com/creatordeepakchaudhari/',
  linkedinlk:'https://www.linkedin.com/in/deepak-chaudhari-79a682150/'
  },
  {id:6,
  name :'Mahima Kulkarni',
  photo :'http://gdurl.com/NAzM',
  year :'TE',
  facebooklk:'',
  twitterlk:'',
  instalk:'',
  linkedinlk:''
  },
  {id:7,
  name :'Sushant Vernekar',
  photo :'http://gdurl.com/EgBO',
  year :'SE',
  facebooklk:'https://www.facebook.com/sushant.vernekar.98',
  twitterlk:'',
  instalk:'https://instagram.com/sushantvernekar?utm_source=ig_profile_share&igshid=co5h4ens4j3j',
  linkedinlk:'https://www.linkedin.com/in/sushant-vernekar-98a00a181'
  },
  {id:8,
  name :'Shreya Mahajan',
  photo :'http://gdurl.com/PfiT',
  year :'SE',
  facebooklk:'https://www.facebook.com/shreya.mahajan.18488',
  twitterlk:'',
  instalk:'',
  linkedinlk:''
  },
  {id:9,
  name :'Riya Parekh',
  photo :'http://gdurl.com/WgQc',
  year :'SE',
  facebooklk:'https://www.facebook.com/riya.parekh.9655',
  twitterlk:'',
  instalk:'https://www.instagram.com/riyaparekh_09/',
  linkedinlk:''
  },
  {id:10,
  name :'Shreya Kajbaje',
  photo :'http://gdurl.com/GRYw',
  year :'SE',
  facebooklk:'https://www.facebook.com/profile.php?id=100009966094664',
  twitterlk:'',
  instalk:'https://www.instagram.com/shreya_k9_/',
  linkedinlk:'https://www.linkedin.com/in/shreya-kajbaje-b89b2717b/'
  },
  {id:11,
  name :'Priya Yashraj',
  photo :'http://gdurl.com/118R',
  year :'SE',
  facebooklk:'',
  twitterlk:'',
  instalk:'https://www.instagram.com/priya_yashraj18/',
  linkedinlk:''
  }
];
