import {Displayinfo} from '../displayinfo';
export const List: Displayinfo[] =[
  {id:1,
  name :'Deepak Gajarmal',
  photo :'http://gdurl.com/c7yG',
  year :'Head',
  facebooklk:'https://www.facebook.com/deepak.wes',
  twitterlk:'',
  instalk:'https://www.instagram.com/deepak_gajarmal/',
  linkedinlk:''
  },
  {id:2,
  name :'Vedant Kashyape',
  photo :'http://gdurl.com/ee1C',
  year :'BE',
  facebooklk:'https://www.facebook.com/vedant.kashyape',
  twitterlk:'',
  instalk:'https://www.instagram.com/vedant_kashyape/',
  linkedinlk:'https://www.linkedin.com/in/vedant-kashyape-b1134954/'
  },
  {id:3,
  name :'Abhishek Karanjekar',
  photo :'http://gdurl.com/iLVZ',
  year :'BE',
  facebooklk:'',
  twitterlk:'https://twitter.com/abhikar17',
  instalk:'https://www.instagram.com/abhi_aviator17/',
  linkedinlk:'https://www.linkedin.com/in/abhishek-karanjekar-774793168/'
  },
  {id:4,
  name :'Mugdha Gumphekar',
  photo :'http://gdurl.com/Whml',
  year :'TE',
  facebooklk:'https://www.facebook.com/mugdha.gumphekar',
  twitterlk:'',
  instalk:'https://www.instagram.com/mugdha_2598/',
  linkedinlk:''
  },
  {id:5,
  name :'Tejashree Pathak',
  photo :'http://gdurl.com/bgskx',
  year :'SE',
  facebooklk:'',
  twitterlk:'',
  instalk:'https://www.instagram.com/pathak.tejashree/',
  linkedinlk:''
  },
  {id:6,
  name :'Jui Godse',
  photo :'http://gdurl.com/9DQ9',
  year :'SE',
  facebooklk:'https://www.facebook.com/jui.godse',
  twitterlk:'',
  instalk:'https://www.instagram.com/juigodse/',
  linkedinlk:''
  },
  {id:7,
  name :'Siddhi Deshmukh',
  photo :'http://gdurl.com/QttM',
  year :'SE',
  facebooklk:'https://www.facebook.com/siddhi.deshmukh.9638',
  twitterlk:'',
  instalk:'https://www.instagram.com/_musical_soul__/',
  linkedinlk:''
  }
];
