import {Displayinfo} from '../displayinfo';
export const List: Displayinfo[] =[
  {id:1,
  name :'Sanjana Bhot',
  photo :'http://gdurl.com/PD0L',
  year :'Head',
  facebooklk:'https://www.facebook.com/sanjana.bhot.5',
  twitterlk:'',
  instalk:'https://instagram.com/sanjana.bhot?utm_source=ig_profile_share&igshid=1eqd53atz240',
  linkedinlk:'https://www.linkedin.com/in/sanjana-bhot-470a42168'
  },
  {id:2,
  name :'Sayli Bhoge',
  photo :'http://gdurl.com/DFsn',
  year :'BE',
  facebooklk:'https://www.facebook.com/avanti.sharma.908',
  twitterlk:'',
  instalk:'https://www.instagram.com/sayli7777/',
  linkedinlk:'linkedin.com/in/sayli-bhoge-237572132'
  },
  {id:3,
  name :'Aniket Suryawanshi',
  photo :'http://gdurl.com/l2vX',
  year :'BE',
  facebooklk:'https://www.facebook.com/aniket.suryawanshi.908',
  twitterlk:'',
  instalk:'https://www.instagram.com/smartgeek_aks/',
  linkedinlk:''
  },
  {id:4,
  name :'Kaustubh Unhale',
  photo :'http://gdurl.com/5Vv3g',
  year :'TE',
  facebooklk:'https://www.facebook.com/kadbond007',
  twitterlk:'https://twitter.com/awesomedotkad',
  instalk:'https://instagram.com/awesomedotkad',
  linkedinlk:'https://www.linkedin.com/in/kaustubhbunhale'
  },
  {id:5,
  name :'Vaishnavi Choukwale',
  photo :'http://gdurl.com/m0Hl',
  year :'TE',
  facebooklk:'https://www.facebook.com/vaishnavi.choukwale',
  twitterlk:'',
  instalk:'https://www.instagram.com/vaishnavi_choukwale/',
  linkedinlk:'https://www.linkedin.com/in/vaishnavi-choukwale-250b69137/'
  },
  {id:6,
  name :'Sharayu Sabale',
  photo :'http://gdurl.com/Dndd',
  year :'SE',
  facebooklk:'https://www.facebook.com/sharayu.sable.39',
  twitterlk:'',
  instalk:'https://www.instagram.com/sharayu_sable/',
  linkedinlk:''
  },
  {id:7,
  name :'Rutuja Chavan',
  photo :'http://gdurl.com/4Dcg',
  year :'SE',
  facebooklk:'',
  twitterlk:'',
  instalk:'https://www.instagram.com/rutujaa_chavan/',
  linkedinlk:''
  },
  {id:8,
  name :'Ashwini Agarwal',
  photo :'http://gdurl.com/PJWa',
  year :'SE',
  facebooklk:'',
  twitterlk:'',
  instalk:'https://www.instagram.com/ashwiniagrawal123/',
  linkedinlk:''
  }
];
